import React from 'react';
import { TreeRecommendation } from '@/lib/types';

interface PlantationRecommendationsProps {
  recommendations: TreeRecommendation[];
}

export const PlantationRecommendations: React.FC<PlantationRecommendationsProps> = ({ recommendations }) => {
  if (!recommendations || recommendations.length === 0) {
    return null;
  }

  return (
    <div className="mt-12">
      <h2 className="text-2xl font-bold text-gray-900 mb-6 flex items-center gap-2">
        <span className="text-nature-600">AI</span> Plantation Recommendations
      </h2>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {recommendations.map((tree, index) => (
          <div key={index} className="bg-white rounded-2xl p-6 shadow-sm border border-gray-100 flex flex-col h-full hover:shadow-md transition-shadow">
            <div className="flex justify-between items-start mb-4">
              <div>
                <h3 className="text-lg font-bold text-gray-900">{tree.speciesName}</h3>
                <p className="text-sm italic text-gray-500">{tree.scientificName}</p>
              </div>
              <div className="bg-nature-50 text-nature-700 px-2 py-1 rounded text-xs font-bold uppercase tracking-wider">
                {tree.nativeStatus}
              </div>
            </div>
            
            <p className="text-gray-600 text-sm mb-6 flex-grow">
              {tree.description}
            </p>
            
            <div className="space-y-4 pt-4 border-t border-gray-50">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <p className="text-xs text-gray-400 uppercase font-semibold">Survival Prob.</p>
                  <div className="flex items-center gap-2">
                    <div className="flex-grow bg-gray-100 h-2 rounded-full overflow-hidden">
                      <div 
                        className="bg-green-500 h-full" 
                        style={{ width: `${tree.survivalProbability}%` }}
                      ></div>
                    </div>
                    <span className="text-sm font-bold text-gray-700">{tree.survivalProbability}%</span>
                  </div>
                </div>
                <div>
                  <p className="text-xs text-gray-400 uppercase font-semibold">Suitability</p>
                  <div className="flex items-center gap-2">
                    <div className="flex-grow bg-gray-100 h-2 rounded-full overflow-hidden">
                      <div 
                        className="bg-blue-500 h-full" 
                        style={{ width: `${tree.suitabilityScore}%` }}
                      ></div>
                    </div>
                    <span className="text-sm font-bold text-gray-700">{tree.suitabilityScore}%</span>
                  </div>
                </div>
              </div>

              <div className="flex flex-wrap gap-2">
                <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full uppercase ${
                  tree.oxygenEfficiency === 'high' ? 'bg-emerald-100 text-emerald-700' :
                  tree.oxygenEfficiency === 'medium' ? 'bg-amber-100 text-amber-700' :
                  'bg-blue-100 text-blue-700'
                }`}>
                  {tree.oxygenEfficiency} Oxygen
                </span>
              </div>

              <div className="space-y-2">
                <div className="flex items-start gap-2">
                  <span className="text-xs font-semibold text-gray-500 w-16 shrink-0">Soil:</span>
                  <span className="text-xs text-gray-600">{tree.soilSuitability}</span>
                </div>
                <div className="flex items-start gap-2">
                  <span className="text-xs font-semibold text-gray-500 w-16 shrink-0">Climate:</span>
                  <span className="text-xs text-gray-600">{tree.climateSuitability}</span>
                </div>
              </div>
            </div>
          </div>
        ))}
      </div>
      <p className="mt-4 text-xs text-gray-400 italic">
        * Recommendations generated by AI based on local environmental data and forestry research.
      </p>
    </div>
  );
};
